title: ididdidi
google_analytics: G-VFZN9EWPJN
theme: jekyll-theme-hacker

collections:
    pages:
        output: true
        permalink: /:path
    posts:
        output: true
        permalink: /:categories/:title
    projects:
        output: true
        permalink: /:categories/:title
    mytags:
        output: true
        permalink: /:path
